language: android
android:
  components:
    - build-tools-28.0.2

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml

addons:
  sonarcloud:
    organization: "asvid-github"
    token:
      secure: $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

script:
  - ./gradlew clean testDevDebugUnitTest lintDevDebug jacocoTestReport coveralls -Dscan